In [71]:
import pandas as pd
import numpy as np
import seaborn as sns

In [72]:
car=pd.read_csv('quikr_car.csv')

In [73]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [74]:
car.shape

(892, 6)

In [75]:
car.info

<bound method DataFrame.info of                                        name    company  year          Price  \
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000
..                                      ...        ...   ...            ...
887                                      Ta       Tara  zest       3,10,000
888                     Tata Zest XM Diesel       Tata  2018       2,60,000
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000

     kms_driven fuel_type
0    45,000 kms    Petrol
1        40 kms    Diesel
2    22,000 kms    Petrol
3    28,000 kms    Petrol
4    36,000 kms    Diesel
..          ...       ...
887         NaN       NaN
888  27,000 kms    Diesel
889  40,000 kms    Diesel
890      Petrol       NaN
891      Petrol       NaN

[892 rows x 6 columns]>

In [76]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [77]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [78]:
backup=car.copy()

In [79]:
# FIXED ORDER: First filter for numeric years, then convert to int
print("\nFiltering for numeric years...")
car = car[car['year'].str.isnumeric()]

print("After filtering for numeric years:")
car.info()

Filtering for numeric years...
After filtering for numeric years:
<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    object
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 46.0+ KB

In [80]:
car=car[car['year'].str.isnumeric()]

In [81]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    object
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 46.0+ KB

In [82]:
car=car[car['Price']!='Ask For Price']

In [83]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [84]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    object
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(1), object(5)
memory usage: 44.8+ KB

In [85]:
car['kms_driven']=car['kms_driven'].str.split().str.get(0).str.replace(',','')

In [86]:
car=car[car['kms_driven'].str.isnumeric()]

In [87]:
car['kms_driven']=car['kms_driven'].astype(int)

In [88]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    object
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.7+ KB

In [89]:
car=car[~car['fuel_type'].isna()]

In [90]:
car['name']=car['name'].str.split().str.slice(start=0,stop=3).str.join(' ')

In [91]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [92]:
car=car.reset_index(drop=True)

In [93]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [94]:
car.describe()

              Price     kms_driven
count  8.160000e+02     816.000000
mean   4.117176e+05   46275.531863
std    4.751844e+05   34297.428044
min    3.000000e+04       0.000000
25%    1.750000e+05   27000.000000
50%    2.999990e+05   41000.000000
75%    4.912500e+05   56818.500000
max    8.500003e+06  400000.000000

In [95]:
car=car[car['Price']<6e6].reset_index(drop=True)

In [96]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [97]:
car.to_csv('Cleaned_Car_data.csv')

In [98]:
X= car.drop(columns='Price')
y=car['Price']

In [99]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [100]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [101]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [102]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [103]:
lr=LinearRegression()

In [104]:
pipe=make_pipeline(column_trans,lr)

In [105]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [106]:
y_pred=pipe.predict(X_test)

In [107]:
y_pred

array([ 216908.40857749,   -5332.62033994,  111421.66385949,
        326647.48293904,  299726.1080135 ,  426890.20037082,
        299167.21485659,  201830.6481729 ,  430202.46559758,
        219878.75232457,  696838.45411383,  480086.5791003 ,
       1371812.48835897,  553638.62565653,  158302.11065737,
        442950.36920464,  237239.49949082,  364793.24944547,
        199183.29970637,   94338.26492157,  358025.2916668 ,
       1559377.83384966,  634487.04152153,  394514.04092113,
        383122.43377438,  436391.86471961,  495430.04510811,
        284710.35553272,  281055.82644469,  358169.41750213,
        234098.8107277 ,  496112.36307508,  181451.06123617,
        455749.17528656,  307773.78664353, 1322792.16827631,
         70288.83004546,  569480.80057014,  500986.17050633,
        135644.41387708,  291637.99213639,  425426.00492708,
        465526.38539243,  307837.80953503,  259472.82901979,
        338537.71004222,  574883.3711366 ,  368051.18200735,
        201428.13729521,  130997.38901553,  291671.53716382,
        295106.59494644,  305854.74701936,  429976.5554226 ,
        162179.99442115,  -13480.53148385,  274612.02054493,
        331674.12083708,  415803.14420889,  196043.73245081,
        423784.88978924, -130183.35348491,  392096.94901537,
         59405.73443267,  364302.74085977,  770263.5961005 ,
        194410.85996722,  510227.52771901,  510103.19676472,
       1611495.00797365,  498988.95171777,  247379.46566482,
        359094.27355674,  -53887.27115685,   93529.26703745,
        190008.64024397,  475285.29343676,  368645.98439714,
       -170718.81370787,  433997.713097  ,  240694.93242785,
        163103.2447846 ,  520042.75668263,  729727.75412431,
        466284.95054876,  432727.38005364,   67332.6582185 ,
        216020.80850984,  391725.2276348 ,  388387.22308978,
        226785.17975692,  261850.33914861,   79162.10081933,
        843774.95287153,  389297.91920816,  667962.96511381,
        617223.90312158, -128365.05582323,  415715.0838693 ,
        526900.36901703,  600810.30910195,  161776.70775579,
        367394.18221004,  -68337.93810385,  255770.20506258,
        282791.31590854,  285557.96270712,  330203.04783735,
        294708.71652773,  114359.32907595,   98145.97803722,
        404729.11390331,  313744.32954971,  288767.48305306,
        335472.24620519,  494748.30956466,  273972.13574299,
        471303.07834297,  321818.88829931,  325169.74178086,
        633475.74510715,   38058.74290846,  338786.81701674,
        935363.07580975,  188992.36254768,  107949.51442623,
        342593.86317911,  210192.29520421,  244108.56525147,
        521113.45329495,  419211.36969531,  180397.37814473,
        418043.97910892,  339037.13519713,  271494.75848   ,
        581969.5036014 ,  599733.2485965 ,  311714.72321422,
        442950.36920464,  173751.89010295,  233839.64888699,
         77516.92330646,  309030.17873663,  157775.64361038,
       2231638.84026687,  714938.9943046 ,  118959.46097923,
        202737.60725679,  411415.99417509,  387713.14376076,
        208756.125673  ,  647564.29122096,  676709.00952307,
        300987.6106244 ,  309030.17873663,  770263.5961005 ,
       1174579.8528994 ,  428433.37789671,  573945.6082634 ,
        157768.12817958,  302463.4028554 ,  588275.88821151,
        305854.74701936])

In [108]:
r2_score(y_test,y_pred)

0.5755285983846213

In [109]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [110]:
np.argmax(scores)

np.int64(302)

In [111]:
scores[np.argmax(scores)]

0.8991116065992623

In [112]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8991116065992623

In [113]:
import pickle

In [114]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [115]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([456822.45072909])